### PR TITLE
Remove confusing/duplicate/buggy make target

### PR DESCRIPTION
**Pull request by SudoBrendan**
Removes `unit-test-go` make target, which does not run commands like `make generate` before being run, leading devs to think this is a legitimate path to execute. This simplifies our make targets and makes it clear which target to run for testing purposes, in short, you should always run `make test-go`.

This PR also addresses the `.PHONY` section, and alphabetizes all `make` targets for more clarity.

### CODE REVIEW

**Review by SrinivasAtmakuri — APPROVED** [review]
LGTM

**Review by tsatam — APPROVED** [review]
LGTM

On the topic of cleanup, the PHONY section at the bottom of the Makefile contains targets that don't exist (likely inherited from ARO-RP?)

**Comment by safwank97** [comment]
LGTM

**Comment by SudoBrendan** [comment]
> LGTM
> 
> On the topic of cleanup, the PHONY section at the bottom of the Makefile contains targets that don't exist (likely inherited from ARO-RP?)

fixed, also alphabetized all make targets.

**Review by tsatam — APPROVED** [review]

**Review by jhoreman — APPROVED** [review]

**Pull request closed without merging**
