### PR TITLE
ARO-12099: Add unit test for applyInstallConfigCustomisations()

### PR DESCRIPTION
**Pull request by zaneb**
Most of the changes to eliminate the installer fork repo will be within this function, so creating a unit test scaffold will allow us to test those changes in a controlled environment.

Note that this PR currently contains patches to the vendored installer that need to be upstreamed (in openshift/installer#9201) before this can merge.

Run the test with the command:

```
go test -tags aro ./pkg/installer/...
```

### CODE REVIEW

**Comment by zaneb** [comment]
/retitle ARO-12099: Add unit test for applyInstallConfigCustomisations()

**Comment by zaneb** [comment]
Tests [show](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer-aro-wrapper/213/pull-ci-openshift-installer-aro-wrapper-main-unit/1859192866308362240/artifacts/test/build-log.txt):
```
✓  pkg/installer (4.083s) (coverage: 23.2% of statements)
```

[Up from](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer-aro-wrapper/207/pull-ci-openshift-installer-aro-wrapper-main-unit/1850978039739977728/artifacts/test/build-log.txt) 4.1% coverage, so it must be doing something.

**Comment by hlipsig** [comment]
Changes LGTM and the upstream dependency has merged.

**Review by jaitaiwan — APPROVED** [review]
LGTM

**Pull request merged**
